# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20170920_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
